In [41]:
import pandas as pd
import numpy as np
import plotly.express as pe

读取数据操作
可以从csv,excel,json,db里读取数据,方法对应read_xxx

输出则对应的DataFrame里的to_xxx

In [82]:
iris=pe.data.iris()
iris.to_csv('iris.csv')

读取常用参数
- usecols 读取哪些列
- names 指定列名
- header 头行
- sep 分隔符
- converters 列数据转换
- true_values=['yes','1'] /false_values=['no','2']
- skiprows 跳过几行
- skip_blanl_lines 跳过空行
- na_values 认为是空值的值

In [28]:


df=pd.read_csv('iris.csv',header=0,usecols=['idx','sepal_length','species_id'],index_col=['idx'],converters={'species_id':lambda id:int(id)-1},
            #    skiprows=2,
               skip_blank_lines=True,na_values={'1.#f'})
df.head()

     sepal_length  species_id
idx
0             5.1           0
1             4.9           0
2             4.7           0
3             4.6           0
4             5.0           0

索引
set_index设置,可设置双层索引,设置索引后不会对修改原有的df,可通过设置inplace来生效

reset_index重制索引,也有inplace参数

常见索引
- RangeIndex 默认的整数索引
- Index 基础索引,普通字符串,整数
- MultiIndex 多层索引,处理高纬
- DatatimeIndex 事件序列索引
- CategoricalIndex 分类索引,自定义排序
> 索引为了方便数据的查找

rename修改索引内容

In [36]:
iris.set_index(['species','species_id'],inplace=True)

In [40]:
iris.reset_index(inplace=True)

In [39]:
iris

                      sepal_length  sepal_width  petal_length  petal_width
species   species_id
setosa    1                    5.1          3.5           1.4          0.2
          1                    4.9          3.0           1.4          0.2
          1                    4.7          3.2           1.3          0.2
          1                    4.6          3.1           1.5          0.2
          1                    5.0          3.6           1.4          0.2
...                            ...          ...           ...          ...
virginica 3                    6.7          3.0           5.2          2.3
          3                    6.3          2.5           5.0          1.9
          3                    6.5          3.0           5.2          2.0
          3                    6.2          3.4           5.4          2.3
          3                    5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# 事件序列索引
num=np.random.randint(2,100,(100,))
date_index=pd.date_range('2022-10-01',freq='D',periods=100)
data_pd=pd.DataFrame(data=num,index=date_index)
data_pd.head()

             0
2022-10-01  85
2022-10-02  86
2022-10-03  24
2022-10-04  13
2022-10-05  36

In [ ]:
data_pd.loc['2022-10-11':'2022-10-20']

             0
2022-10-11   4
2022-10-12  50
2022-10-13  31
2022-10-14   8
2022-10-15  40
2022-10-16  94
2022-10-17  73
2022-10-18  85
2022-10-19   5
2022-10-20  20

In [ ]:
data_pd.resample('W').sum() #重新采样

              0
2022-10-02  171
2022-10-09  263
2022-10-16  262
2022-10-23  352
2022-10-30  182
2022-11-06  442
2022-11-13  429
2022-11-20  259
2022-11-27  424
2022-12-04  487
2022-12-11  298
2022-12-18  330
2022-12-25  286
2023-01-01  318
2023-01-08  391

In [ ]:
cate_index=pd.CategoricalIndex(['S','M','L'],ordered=True)

# size 是默认属性
s=pd.DataFrame(data={'num':[1,2,4,5,6],'sizes':['S','M','M','L','S']})
# 创建分类
s.sizes=pd.Categorical(s.sizes,categories=cate_index)
s.sizes.dtypes

CategoricalDtype(categories=['L', 'M', 'S'], ordered=False, categories_dtype=object)

In [ ]:
iris=pe.data.iris()
iris.species_id=pd.Categorical(iris.species_id,categories=[1,2,3])
# iris.set_index('species_id')
iris.set_index('species_id',inplace=True)
iris.index.value_counts() # 统计索引个数
iris.rename(columns={'species':'id_'})

            sepal_length  sepal_width  petal_length  petal_width        id_
species_id
1                    5.1          3.5           1.4          0.2     setosa
1                    4.9          3.0           1.4          0.2     setosa
1                    4.7          3.2           1.3          0.2     setosa
1                    4.6          3.1           1.5          0.2     setosa
1                    5.0          3.6           1.4          0.2     setosa
...                  ...          ...           ...          ...        ...
3                    6.7          3.0           5.2          2.3  virginica
3                    6.3          2.5           5.0          1.9  virginica
3                    6.5          3.0           5.2          2.0  virginica
3                    6.2          3.4           5.4          2.3  virginica
3                    5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

数据信息
- 查看样本
    - head()
    - tail()
    - sample() 一条随机数据,可指定条数
- info 查看基本信息
- df.dtype 查看数据类型
- df.axes 列内容,行内容

In [111]:
iris.axes

[CategoricalIndex([1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                   ...
                   3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
                  categories=[1, 2, 3], ordered=False, dtype='category', name='species_id', length=150),
 Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
        'species'],
       dtype='object')]

统计信息
- describe 返回统计表
- mean 所有列均值
- corr 列与列之间相关系数
- max,min,abs
- median 中位数
- std 标准差
- var 方差
- mode 众数
- cumprod 连乘
- cumsum
- nunique 去重数量的,不同值
- idxmax,idxmin 每列最大/小的索引名
- skew 样本偏差度 3阶
- kurt 峰度 4阶

In [112]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [115]:
iris[['petal_length','petal_width']].corr()

              petal_length  petal_width
petal_length      1.000000     0.962757
petal_width       0.962757     1.000000

非统计运算
- any/all 配合逻辑判断使用,any一个true就行,all全部为true
- round({'col':4})四舍五入
- nunique 去重值的数量
- isna 是否为空

Series 专有
- value_count 不重复值和个数
- unique 去重的值
- is_uniques 是否去重
- nlargest 最大前n个
- nsmallest 最小前n个
- pct_change 计算与前一行的变化periods设置比数

In [140]:
ps=pd.Series(data=['a',None,None],index=[1,2,3])
ps.nunique()

1

In [144]:
iris.sepal_length.nlargest()

species_id
3    7.9
3    7.7
3    7.7
3    7.7
3    7.7
Name: sepal_length, dtype: float64

In [147]:
vps=pd.Series(data=np.random.randint(1,10,size=(10,)))
vps.pct_change(periods=2)

0         NaN
1         NaN
2   -0.142857
3   -0.500000
4   -0.166667
5    2.500000
6    0.000000
7    0.142857
8   -0.600000
9   -0.500000
dtype: float64

位置计算

- diff 位移差操作
- shift 对数据进行移位,不做任何计算
- rank na_option='bottom'把空值放后面

In [ ]:
vps.shift(4)

0    NaN
1    NaN
2    NaN
3    NaN
4    7.0
5    4.0
6    6.0
7    2.0
8    5.0
9    7.0
dtype: float64

数据选择
- df[col] 选择列 df.col
- df.loc[label] label是(row,col)列不传返回所以列
- df.iloc[loc] 与loc格式相关,只是它使用的数字
- df[5:10] 切片,时间是用的切片
- df[bool]

获得具体值
- at 类似与loc 
- iat 类似与iloc

截取
- truncate before,after两个参数