In [1]:
import pandas as pd

缺失值的认定
一般用np.NaN/np.nan/pd.Na表示;通过设置`pd.options.mode.shuse_inf_as_na=True`.空值主要根据数据类型和后段机制不同而处理,时间类型pd.NaT (Not a Time)

缺失值判断
df.isna/df.isnull;相反的df.notna

缺失值统计
df.isnull().sum()每行/sum(1)每列

缺失行/列
df.isnull().any()返回带空值行/any(1)列

缺失值的操作
1. df.fillna() 参数可以穿字典key列,将不同列替换为不同的缺失值
- limit 只替换第一个

ffill 向前填充,使用前一个有效值填充
bfill 向后填充,使用后一个有效值填充
df.fillna(df.mean()) 填充平均值
df.where(df.isno(),df.mean())
df.replace('col',{np.nan:10})

2. 插值填充
interpolate利用离散函数拟合,估算在点的近似值
- method linear 用线性方法/ quadratic 二次插值

3. 删除缺失值
df.dropna
axis 设置列;how='all'删除所有缺失的行;thresh删除至少两个缺失值的行

缺失值参与计算
- 加法忽略缺失值或将其按0处理,设置skipna跳过
- count不计算缺失值
- group会忽略,可通过设置dropna空值

In [4]:
# 原数据
df = pd.DataFrame({
    'A':['a1', 'a1', 'a2', 'a2'],
    'B':['b1', 'b2', None, 'b2'],
    'C':[1, 2, 3, 4],
    'D':[5, 6, None, 8],
    'E':[5, None, 7, 8]
})

In [ ]:
df.loc[df.isna().any(axis=1)]

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [ ]:
df=df.convert_dtypes()
df.interpolate() # 存在字符串

AxisError: axis 1 is out of bounds for array of dimension 1

In [28]:
df.dropna()

    A   B  C  D  E
0  a1  b1  1  5  5
3  a2  b2  4  8  8

数据替换 replace
- df.replace([1],[2])一一替换
- (0:1,2:2) 字典对应值替换
- ({'a':0,'b':2},100)将a/b两列中的值替换
- {'a',{}}a列中的值替换
- ser.replace([1, 2, 3], method='pad') 将 1，2，3 替换为它们前一个, ffill是它同义词
- ser.replace([1, 2, 3], method='bfill') 将 1，2，3 替换为它们后一个值

字符替换
to_palace='',value='new' 可以使用regex参数


数据修建 clip
df.clip(lower,upper)数据大于upper使用upper,小于lower使用lower,与np.clip一样

重复值
查看重复值 duplicated
- subset 指定列
- keep
    - first 保留第一个,第一次遇到数据为False,之后遇到一模一样就为true
    - last 保留最后一个,最后一个遇到为False前面的true
    - False 只要出现不止一次全部为true

删除重复列 drop_duplicates
- subset
- keep
    - fasle 都不保留只要发现重复
    - first 保留第一次出现记录
    - last 保留最后一次出现的记录
- inplace
- ignore_index  删除中间行会导致所有不连续,pandas会自动调节索引

drop 删除数据
- labels要删除的行或者列,可传列表
- axis 轴方向
- index
- column
- level 索引层级
- inplace
- errors ignore/raise

In [31]:

# 构建多层索引：外层是年份，内层是城市
index = pd.MultiIndex.from_tuples(
    [('2023', '北京'), ('2023', '上海'), ('2024', '北京'), ('2024', '上海')],
    names=['年份', '城市']
)
df = pd.DataFrame({'销量': [100, 150, 120, 180]}, index=index)

print("=== 原始多层索引数据 ===")
print(df)

=== 原始多层索引数据 ===
          销量
年份   城市
2023 北京  100
     上海  150
2024 北京  120
     上海  180

In [34]:
df.drop('北京',level='城市')

          销量
年份   城市
2023 上海  150
2024 上海  180