In [2]:
import pandas as pd
import numpy as np
from plotly import express as pep
iris=pep.data.iris()

多层索引

1. 通过from_xx手动创建,arrys或tuple注意对应位置匹配
2. groupby
3. set_index


df.index
- nlevels 层级数
- levels  层级
- get_level_values(int) 获取n层内容
- drop
df.columns
- nlevels
- levels

In [ ]:
# 注意对应关系
A=[1,1,2,2]
B=['A','B','A','B']
id=pd.MultiIndex.from_arrays([A,B])
pd.DataFrame(data=np.random.randint(1,4,(4)),index=id)
pd.MultiIndex.fr

     0
1 A  1
  B  2
2 A  1
  B  1

In [ ]:
level=np.random.choice(['A','B','C'],size=(150,))
iris['level']=level

,sepal_length,sepal_width,petal_length,petal_width,species,species_id,level
1,4.9,3.0,1.4,0.2,setosa,1,A
5,5.4,3.9,1.7,0.4,setosa,1,A
6,4.6,3.4,1.4,0.3,setosa,1,A
7,5.0,3.4,1.5,0.2,setosa,1,A
10,5.4,3.7,1.5,0.2,setosa,1,A
13,4.3,3.0,1.1,0.1,setosa,1,A
16,5.4,3.9,1.3,0.4,setosa,1,A
17,5.1,3.5,1.4,0.3,setosa,1,A
20,5.4,3.4,1.7,0.2,setosa,1,A
21,5.1,3.7,1.5,0.4,setosa,1,A
24,4.8,3.4,1.9,0.2,setosa,1,A
29,4.7,3.2,1.6,0.2,setosa,1,A
35,5.0,3.2,1.2,0.2,setosa,1,A
40,5.0,3.5,1.3,0.3,setosa,1,A

In [23]:
iris.set_index(['species','level'],inplace=True)

In [39]:
iris_max=iris.groupby(['species','level'],group_keys=True).max()
iris_max.loc['virginica']

       sepal_length  sepal_width  petal_length  petal_width  species_id
level
A               7.9          3.8           6.9          2.5           3
B               7.7          3.4           6.7          2.5           3
C               7.7          3.4           6.3          2.4           3

In [27]:
# 索引
index_arrays = [[1, 1, 2, 2], ['男', '女', '男', '女']]
# 列名
columns_arrays = [['2019', '2019', '2020', '2020'],
                  ['上半年', '下半年', '上半年', '下半年',]]
# 索引转换为多层
index = pd.MultiIndex.from_arrays(index_arrays,
                                  names=('班级', '性别'))
# 列名转换为多层
columns = pd.MultiIndex.from_arrays(columns_arrays,
                                    names=('年份', '学期'))
# 应用到DataFrame中
df = pd.DataFrame([(88,99,88,99),(77,88,97,98),
                   (67,89,54,78),(34,67,89,54)],
                  columns=columns, index=index)
df

年份    2019     2020
学期     上半年 下半年  上半年 下半年
班级 性别
1  男    88  99   88  99
   女    77  88   97  98
2  男    67  89   54  78
   女    34  67   89  54

In [29]:
df.index,df.columns

(MultiIndex([(1, '男'),
             (1, '女'),
             (2, '男'),
             (2, '女')],
            names=['班级', '性别']),
 MultiIndex([('2019', '上半年'),
             ('2019', '下半年'),
             ('2020', '上半年'),
             ('2020', '下半年')],
            names=['年份', '学期']))

多层索引查询

df.loc['idx1'] 查询的一层索引的值

df[('idx1','idx2')] 二级索引查询

df.loc['row_idx',(cidx1,cidx2)] 行列查询

df[df.loc[('idx1','idx2')]>2] 条件查询

df.xs索引内容查询
- df.xs((1, '男')) # 1班男生
- df.xs('2020', axis=1) # 2020年
- df.xs('男', level=1) # 所有男生

In [ ]:
df.loc[1]

年份 2019     2020
学期  上半年 下半年  上半年 下半年
性别
男    88  99   88  99
女    77  88   97  98

In [37]:
df.index

MultiIndex([(1, '男'),
            (1, '女'),
            (2, '男'),
            (2, '女')],
           names=['班级', '性别'])